export const objects = [
  {
    id: 1,
    url: ["./images/object-1.jpg", "./images/object-2.jpg"],
    location: "Paje",
    price: 150,
    size: 1000,
    type: "House",
    to: "Buy",
    desc: "7 min to the beach",
    info: "Big house with 4 bedrooms, 3 bathrooms, big kitchen and 2 living rooms. The house is built this year and modern. The house have a big garden with lot of space.",
  },
  {
    id: 2,
    url: ["./images/object-2.jpg"],
    location: "Paje",
    price: 900,
    size: 200,
    type: "House",
    to: "Rent",
    desc: "3 min to the beach",
    info: "Big house with 3 bedrooms, 2 bathrooms, big kitchen and 1 living rooms. The house is built this year and modern. The house have a big garden with lot of space.",
  },
  {
    id: 3,
    url: ["./images/object-3.jpg"],
    location: "Paje",
    price: 130,
    size: 2500,
    type: "Plot",
    to: "Buy",
    desc: "Beach Front Plot",
    info: "Beach front plot with palms and other trees. Here yoou can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
  {
    id: 4,
    url: ["./images/plotzanzibar.jpg"],
    location: "Paje",
    price: 60,
    size: 1200,
    type: "Plot",
    to: "Buy",
    desc: "Beach Front Plot",
    info: "Beach front plot with palms and other trees. Here yoou can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
  {
    id: 5,
    url: ["./images/beachhousezanzibar.jpg"],
    location: "Jambiani",
    price: 1200,
    size: 300,
    type: "House",
    to: "Rent",
    desc: "Beach Front House",
    info: "Beach front house with pool and palms and other trees. 2 floor house with 5 bedromms, 3bathrooms, 2 living rooms and a big kitchen",
  },
];

export const links = [
  {
    icon: '<i class="fas fa-phone-square"></i>',
    url: "./contact.html",
    text: "Contact & Support",
  },
  {
    icon: '<i class="fas fa-question-circle"></i>',
    url: "./facts.html",
    text: "How does it work?",
  },
  {
    icon: '<i class="fab fa-adversal"></i>',
    url: "./advertisezanzibar.html",
    text: "Advertise on HomeNet",
  },
  {
    icon: '<i class="far fa-building"></i>',
    url: "./rentbusinesszanzibar.html",
    text: "Rent Business",
  },
  {
    icon: '<i class="fas fa-file-signature"></i>',
    url: "./leasinglandzanzibar.html",
    text: "Leasing Land",
  },
  {
    icon: '<i class="fas fa-money-check-alt"></i>',
    url: "./buyhousezanzibar.html",
    text: "Buy Property & Land",
  },
  {
    icon: '<i class="fas fa-handshake"></i>',
    url: "./sellhousezanzibar.html",
    text: "Sell Property & Land",
  },
  {
    icon: '<i class="fas fa-home"></i>',
    url: "./renthousezanzibar.html",
    text: "Rent Property & Land",
  },
];
