export const objects = [
  {
    id: 1,
    url: [
      "./images/object-1.jpg",
      "./images/object-2.jpg",
      "./images/object-3.jpg",
    ],
    location: "Paje",
    price: 150000,
    size: 1000,
    type: "House",
    to: "Buy",
    desc: "3 min to the beach",
    info: "Beach front plot with palms and other trees. Here you can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
  {
    id: 2,
    url: ["./images/object-2.jpg"],
    location: "Paje",
    price: 150,
    size: 2000,
    type: "House",
    to: "Rent",
    desc: "3 min to the beach",
    info: "Beach front plot with palms and other trees. Here yoou can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
  {
    id: 3,
    url: ["./images/object-3.jpg"],
    location: "Paje",
    price: 130000,
    size: 2500,
    type: "Plot",
    to: "Buy",
    desc: "Beach Front Plot",
    info: "Beach front plot with palms and other trees. Here yoou can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
  {
    id: 4,
    url: ["./images/plotzanzibar.jpg"],
    location: "Paje",
    price: 45000,
    size: 1500,
    type: "Plot",
    to: "Buy",
    desc: "Beach Front Plot",
    info: "Beach front plot with palms and other trees. Here yoou can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
  {
    id: 4,
    url: ["./images/plotzanzibar.jpg"],
    location: "Paje",
    price: 45000,
    size: 1500,
    type: "Plot",
    to: "Buy",
    desc: "Beach Front Plot",
    info: "Beach front plot with palms and other trees. Here yoou can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
];

export const links = [
  {
    icon: '<i class="fas fa-phone-square"></i>',
    url: "./contact.html",
    text: "Contact & Support",
  },
  {
    icon: '<i class="fas fa-question-circle"></i>',
    url: "./facts.html",
    text: "How does it work?",
  },
  {
    icon: '<i class="fab fa-adversal"></i>',
    url: "./advertisezanzibar.html",
    text: "Advertise on HomeNet",
  },
  {
    icon: '<i class="far fa-building"></i>',
    url: "./leasingcompanyzanzibar.html",
    text: "Leasing Compaines",
  },
  {
    icon: '<i class="fas fa-file-signature"></i>',
    url: "./leasinglandzanzibar.html",
    text: "Leasing Land",
  },
  {
    icon: '<i class="fas fa-money-check-alt"></i>',
    url: "./buyhousezanzibar.html",
    text: "Buy Property & Land",
  },
  {
    icon: '<i class="fas fa-handshake"></i>',
    url: "./sellhousezanzibar.html",
    text: "Sell Property & Land",
  },
  {
    icon: '<i class="fas fa-home"></i>',
    url: "./renthousezanzibar.html",
    text: "Rent Property & Land",
  },
];
