export const objects = [
  {
    id: 1,
    url: ["./images/object-1.jpg", "./images/object-2.jpg"],
    location: "Paje",
    price: 90,
    size: 1000,
    type: "House",
    to: "Buy",
    desc: "7 min to the beach",
    info: "Big house in Zanzibar for sell with 4 bedrooms, 3 bathrooms, big kitchen and 2 living rooms. The house is built this year and modern. The house have a big garden with lot of space.",
  },
  {
    id: 2,
    url: ["./images/object-2.jpg"],
    location: "Paje",
    price: 1000,
    size: 200,
    type: "House",
    to: "Rent",
    desc: "3 min to the beach",
    info: "Big house in Paje Zanzibar with 3 bedrooms, 2 bathrooms, big kitchen and 1 living rooms. The house is built this year and modern. The house have a big garden with lot of space.",
  },
  {
    id: 3,
    url: ["./images/object-3.jpg"],
    location: "Paje",
    price: 130,
    size: 2500,
    type: "Land",
    to: "Buy",
    desc: "Beach front plot",
    info: "Beach front plot in Paje Zanzibar with palms and other trees. Here yoou can build club, restaurant and bangalow , barhroomhouse and hotell. Located in were popular area with lot of thigs to do",
  },
  {
    id: 4,
    url: ["./images/plotzanzibar.jpg"],
    location: "Pemba",
    price: 55,
    size: 1200,
    type: "Land",
    to: "Buy",
    desc: "Beach front plot",
    info: "Beach front plot in Zanzibar Pemba with palms and other trees. Here yoou can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
  {
    id: 5,
    url: ["./images/beachhousezanzibar.jpg"],
    location: "Jambiani",
    price: 1200,
    size: 300,
    type: "House",
    to: "Rent",
    desc: "Beach front house",
    info: "Beach front house for rent in Jambiani Zanzibar with pool. 5 bedrooms, 2 living room, 3 bathrooms and a big kitchen",
  },
  {
    id: 6,
    url: ["./images/landpaje-1.jpg", "./images/my-2.jpg"],
    location: "Paje",
    price: 16,
    size: 1400,
    type: "Land",
    to: "Buy",
    desc: "5 min to the beach",
    info: "Big land in Paje Zanzibar and close to the main road. Close to the village and paje beach. Here you can build smaller houses for business or a big house with pool.",
  },
  {
    id: 7,
    url: [
      "./images/buylandpaje-3.jpg",
      "./images/uk.png",
      "./images/buylandpaje-2.jpg",
    ],
    location: "Paje",
    price: 13,
    size: 900,
    type: "Land",
    to: "Buy",
    desc: "5 min to the beach",
    info: "Big land in Paje Zanzibar and close to the main road. Close to the village and paje beach. Here you can build smaller houses for business or a big house with pool.",
  },
  {
    id: 8,
    url: [
      "./images/beachplotzanzibar.jpg",
      "./images/beachplotzanzibar-1.jpg",
      "./images/beachplotzanzibar-2.jpg",
    ],
    location: "Paje",
    price: 125,
    size: 4900,
    type: "Land",
    to: "Buy",
    desc: "Beach side plot",
    info: "Big land in Paje Zanzibar, 1min walk to the beach and close to the main road. Close to the village located at paje beach side. Here you can build hotell or resort,  houses for business or a 2- 3 big house with pool.",
  },

  {
    id: 9,
    url: ["./images/my-1.jpg", "./images/my-2.jpg"],
    location: "Paje",
    price: 7,
    size: 555,
    type: "Land",
    to: "Buy",
    desc: "5 min to the beach",
    info: "Nice plot in Paje Zanzibar and very close to the main road. Close to the village and paje beach. Here you can build 2 smaller houses for business or a big house with big garden.",
  },
  {
    id: 10,
    url: ["./images/mina3.JPG", "hh.png"],
    location: "Paje",
    price: 6,
    size: 1040,
    type: "Land",
    to: "Buy",
    desc: "7 min to the beach",
    info: "Big land in Paje are name Domo kuchu juu on the way to Jambiani only 2 min with car. Perfect for a house with big garden. The plot is located on the other side of the road to the beach. 3 min in the forest with car. There is lot of houses there and some under construction",
  },
  {
    id: 11,
    url: ["./images/mina3.JPG", "./images/hh.png"],
    location: "Paje",
    price: 10,
    size: 2000,
    type: "Land",
    to: "Buy",
    desc: "7 min to the beach",
    info: "Big land in Paje are name Domo kuchu juu on the way to Jambiani only 2 min with car. Perfect for a house with big garden. The plot is located on the other side of the road to the beach. 3 min in the forest with car. There is lot of houses there and some under construction",
  },
];

export const links = [
  {
    icon: '<i class="fas fa-phone-square"></i>',
    url: "./contact.html",
    text: "Contact & Support",
  },
  {
    icon: '<i class="fas fa-question-circle"></i>',
    url: "./facts.html",
    text: "How does it work?",
  },
  {
    icon: '<i class="fab fa-adversal"></i>',
    url: "./advertisezanzibar.html",
    text: "Advertise on ZanziHome",
  },
  {
    icon: '<i class="far fa-building"></i>',
    url: "./rentbusinesszanzibar.html",
    text: "Rent Business",
  },
  {
    icon: '<i class="fas fa-file-signature"></i>',
    url: "./leasinglandzanzibar.html",
    text: "Leasing Land",
  },
  {
    icon: '<i class="fas fa-money-check-alt"></i>',
    url: "./buyhousezanzibar.html",
    text: "Buy Property & Land",
  },
  {
    icon: '<i class="fas fa-handshake"></i>',
    url: "./sellhousezanzibar.html",
    text: "Sell Property & Land",
  },
  {
    icon: '<i class="fas fa-home"></i>',
    url: "./rentouthousezanzibar.html",
    text: "Rent Out Property & Land",
  },
  {
    icon: '<i class="fas fa-home"></i>',
    url: "./renthousezanzibar.html",
    text: "Rent Property & Land",
  },
];
